version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
  AfterAllowTraffic:
    - location: scripts/asg.sh
      timeout: 300
      runas: root
  BeforeBlockTraffic:
    - location: scripts/sleeptime.sh
      timeout: 300
      runas: root
  AfterBlockTraffic:
    - location: scripts/oldasg.sh
      timeout: 300
      runas: root
       
